# Generated by Django 5.2 on 2025-05-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='pay_period',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
