# Generated by Django 5.2 on 2025-06-03 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='pay_period',
        ),
    ]
