# Generated by Django 5.2 on 2025-06-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payroll_net_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='year',
        ),
    ]
